# 게임 설정 파일
game:
  name: "Multiplayer Vehicle Combat"
  version: "1.0.0"
  maxPlayers: 8
  minPlayersToStart: 1
  gameMode: "deathmatch"
  
server:
  port: 3001
  host: "0.0.0.0"  # 모든 인터페이스에서 접근 허용 (외부 접근용)
  tickRate: 60  # 서버 업데이트 주기 (Hz)
  
# 네트워크 설정
network:
  allowExternalAccess: true  # 외부 접근 허용 여부
  cors:
    enabled: true
    origins: "*"  # 허용할 도메인 (* = 모든 도메인)
  publicUrl: ""  # 공개 URL (비어있으면 자동 감지)
  
world:
  size: 400
  terrainDetail: 100
  waterLevel: -5
  gravity: -9.81
  
# 광고판 설정
billboards:
  enabled: true
  count: 5  # 광고판 개수
  width: 40  # 광고판 너비
  height: 20  # 광고판 높이
  thickness: 2  # 광고판 두께
  health: 80  # 광고판 체력 (총알 8발 정도로 파괴)
  minDistance: 80  # 광고판 간 최소 거리
  images:
    front: "assets/billboards/front.svg"  # 앞면 이미지
    back: "assets/billboards/back.svg"    # 뒷면 이미지
    # 여러 이미지 사용 시 배열로 설정 가능
    # front: 
    #   - "assets/billboards/ad1.jpg"
    #   - "assets/billboards/ad2.jpg"
    # back:
    #   - "assets/billboards/ad3.jpg"
    #   - "assets/billboards/ad4.jpg"
  
vehicles:
  maxSpeed: 100
  acceleration: 50
  turnSpeed: 3.0
  rollSpeed: 2.5
  pitchSpeed: 2.5
  yawSpeed: 2.0
  health: 100
  colors:
    - "#FF0000"  # 빨강
    - "#00FF00"  # 초록
    - "#0000FF"  # 파랑
    - "#FFFF00"  # 노랑
    - "#FF00FF"  # 마젠타
    - "#00FFFF"  # 시안
    - "#FFA500"  # 주황
    - "#800080"  # 보라
  
weapons:
  machineGun:
    damage: 10
    fireRate: 10  # 초당 발사 수
    bulletSpeed: 200
    range: 300
    bulletLifetime: 3  # 초
    
physics:
  airResistance: 0.98
  groundFriction: 0.95
  collisionDamping: 0.5
  
effects:
  explosionDuration: 2  # 초
  bulletTrailLength: 10
  
camera:
  followDistance: 50
  followHeight: 20
  smoothing: 0.1 